{
    "name": "HR Salary Request",
    "version": "14.0.1.0.1",
    "author": "Hadooc",
    "depends": [
        "request",
        "hr_base",
        "hr_employee_number",
        "request_refuse",
        "hr_payroll",
        "hr_contract",
        "res_company_fax",
        "company_manager",
        "report_xlsx",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/salary_request_security.xml",
        "data/hr_salary_request_stage_data.xml",
        "data/mail_data.xml",
        "report/comprehensive_detailed_definition.xml",
        "report/definition_of_total_report.xml",
        "report/fixing_salary_report.xml",
        "report/history_salary_reports.xml",
        "report/no_salary_report.xml",
        "views/hr_salary_request_views.xml",
        "views/request_stage_views.xml",
    ],
    "installable": True,
    "license": "AGPL-3",
}
