{
    "name": "Deputation Management",
    "version": "14.0.1.0.1",
    "author": "Hadooc",
    "depends": [
        "base_address_city",
        "request_refuse",
        "hr_employee_number",
        "request",
        "hr_base",
        "hr_obligation",
        "hr_public_holidays",
        "web_digital_sign",
    ],
    "data": [
        "security/hr_deputation_security.xml",
        "security/ir.model.access.csv",
        "data/hr_deputation_data.xml",
        "data/mail_data.xml",
        "report/deputation_report_template.xml",
        "views/menu.xml",
        "views/request_stage_views.xml",
        "views/hr_views.xml",
        "views/hr_deputation_views.xml",
        "views/hr_deputation_setting_views.xml",
        "views/hr_deputation_cancellation_view.xml",
        "views/hr_deputation_cut_views.xml",
        "views/hr_deputation_extension_view.xml",
        "views/res_users_views.xml",
    ],
    "demo": ["data/hr_deputation_demo.xml"],
    "installable": True,
    "license": "AGPL-3",
}
