{
    "name": "Clearance Reports",
    "version": "14.0.1.0.0",
    "author": "Hadooc",
    "depends": ["transportation", "report_xlsx_helper"],
    "data": [
        "security/clearance_dashboard_security.xml",
        "security/ir.model.access.csv",
        "data/clearance_reports_data.xml",
        "report/clearance_states_template.xml",
        "report/shipping_order_template.xml",
        "report/payments_invoices_template.xml",
        "report/report_clearance_request.xml",
        "report/clearance_warehouse_template.xml",
        "report/clearance_request_reports.xml",
        "report/transport_order_template.xml",
        "report/clearance_report_views.xml",
        "report/clearance_request_transport_template.xml",
        "data/mail_template.xml",
        "wizard/clearance_request_wizard_views.xml",
    ],
    "installable": True,
    "license": "AGPL-3",
}
