{
    "name": "Farha Custom",
    "version": "14.0.1.0.6",
    "author": "Hadooc",
    "depends": [
        "hr_payroll_base",
        "report_xlsx",
        "hr_employee_number",
        "hr_base",
        "account",
        "dms",
        "hr_payroll_loan",
        "hr_bonus",
        "hr_fleet",
        "hr_holidays_request",
        "company_manager",
        "hr_expense_states",
        "purchase",
        "sale",
        "hr_training",
        "hr_salary_request",
        "real_estate",
        "hr_payment_request",
        "transportation",
        "point_of_sale",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/farha_data.xml",
        "report/payslip_reports.xml",
        "report/sale_report_templates.xml",
        "report/report.xml",
        "report/definition_of_total_report.xml",
        "report/comprehensive_detailed_definition.xml",
        "report/fixing_salary_report.xml",
        "views/hr_bonus_views.xml",
        "views/ir_attachment_views.xml",
        "views/hr_payslip_views.xml",
        "views/res_company_views.xml",
        "views/account_move_views.xml",
        "views/account_payment_views.xml",
        "views/purchase_order_views.xml",
        "views/hr_fleet_views.xml",
        "views/hr_leave_allocation_views.xml",
        "views/hr_expense_views.xml",
        "views/realestate_contract_views.xml",
        "views/mail_activity_views.xml",
        "views/hr_employee_views.xml",
        "views/hr_payment_request_views.xml",
        "views/pos_config_view.xml",
    ],
    "installable": True,
    "license": "AGPL-3",
}
