from . import clearance_setting
from . import clearance_request
from . import transportation
from . import calendar
from . import res_company
from . import account_payment
from . import hr_employee
from . import fleet
from . import account_move
from . import sale_order
from . import ir_attachment
