from . import hr_payslip
from . import res_company
from . import account_payment
from . import account_move
from . import hr_loan
from . import fleet_vehicle
from . import hr_leave_allocation
from . import hr_bonus
from . import hr_expense
from . import hr_salary_request
from . import realestate_contract
from . import hr_employee
from . import product_product
from . import res_partner
