{
    "name": "Transportation",
    "version": "14.0.0.0.8",
    "author": "Eng. Fares",
    "depends": ["clearance", "hr_fleet_information", "calendar", "request", "rating"],
    "data": [
        "security/transportation_security.xml",
        "security/ir.model.access.csv",
        "data/transportation_data.xml",
        "report/account_payment_report.xml",
        "report/way_bill_template.xml",
        "report/transportation_reports.xml",
        "data/transportation_mail_template_data.xml",
        "views/transportation_templates_rating.xml",
        "views/clearance_request_views.xml",
        "views/transportation_views.xml",
        "views/clearance_request_shipment_type_views.xml",
        "views/transportation_setting_views.xml",
        "views/hr_employee_views.xml",
        "views/fleet_views.xml",
        "views/account_payment_views.xml",
    ],
    "installable": True,
    "license": "AGPL-3",
}
