{
    "name": "Farha Custom Icon",
    "version": "14.0.0.0.0",
    "author": "Eng. Fares",
    "depends": [
        "website",
        "account",
        "contacts",
        "request",
        "im_livechat",
        "ks_dashboard_ninja",
        "clearance",
        "hr_expense",
        "purchase",
        "point_of_sale",
        "hr_attendance",
        "calendar",
        "crm",
        "dms",
        "mail",
        "im_livechat",
        "stock",
        "sale",
        "transportation",
        "fleet",
        "real_estate",
        "announcements",
        "help_desk",
        "hr_recruitment",
        "employee_housing",
        "project",
        "crm_icon",
        "hotel_reservation",
        "hotel",
        "hotel_room",
        "hotel_housekeeping",
        "survey",
    ],
    "data": ["views/menu_icon_views.xml"],
    "installable": True,
    "license": "AGPL-3",
}
