# See LICENSE file for full copyright and licensing details.

{
    "name": "Hotel Reservation Management",
    "version": "14.0.1.0.1",
    "author": "Eng. Fares",
    "category": "Generic Modules/Hotel Reservation",
    "license": "AGPL-3",
    "summary": "Manages Guest Reservation & displays Reservation Summary",
    "website": "https://github.com/OCA/vertical-hotel",
    "depends": [
        "hotel_customer",
        "stock",
        "mail",
        "hotel_housekeeping",
        "rating",
        "report_pdf_preview",
        "invoice_whatsapp_integration",
        "account_check_printing",
        'web_ar',
    ],
    "demo": ["demo/hotel_reservation_demo.xml"],
    "data": [
        "security/hotel_reservation_security.xml",
        "security/ir.model.access.csv",
        "data/payment_method_data.xml",
        "data/hotel_scheduler.xml",
        "data/hotel_reservation_sequence.xml",
        "data/email_template_view.xml",
        "data/hotel_reservation_data.xml",
        "views/hotel_reservation_view.xml",
        "report/checkin_report_template.xml",
        "report/checkout_report_template.xml",
        "report/room_max_report_template.xml",
        "report/hotel_reservation_report_template.xml",
        "report/booking_summary_template.xml",
        "report/rent_contract_template.xml",
        "report/booking_rent_folio_template.xml",
        "report/report_insurance_receipt_template.xml",
        "report/report_insurance_payment_template.xml",
        "report/report_payment_receipt_template.xml",
        "report/hotel_reservation_invoice_template.xml",
        'report/report_payment_payment_template.xml',
        "report/report_view.xml",
        "views/assets.xml",
        "views/account_views.xml",
        "views/hotel_reservation_settings_views.xml",
        "wizards/hotel_reservation_wizard.xml",
        "wizards/hotel_reservation_finish_wizard.xml",
        "wizards/hotel_reservation_check_wizard.xml",
        "wizards/reservation_change_room_wizard.xml",
        "wizards/reservation_cancel_wizard.xml",
        "views/menu.xml",
        "views/apartments_views.xml",
        "views/hotel_reservation_rating_views.xml",
        "views/res_partner_views.xml",
        "views/hotel_housekeeping_views.xml",
    ],
    "qweb": ["static/src/xml/hotel_room_summary.xml"],
    "external_dependencies": {"python": ["dateutil", "ummalqura"]},
    "installable": True,
}
