{
    "name": "Document Management System",
    "version": "14.0.0.0.0",
    "author": "Eng. Fares",
    "summary": "DMS",
    "depends": ["web", "base", "mail", "dashboard_base"],
    "data": [
        "security/dms_security.xml",
        "security/multi_company_security.xml",
        "security/ir.model.access.csv",
        "data/dms_data.xml",
        "data/settings_data.xml",
        "data/attachment_mail_template_data.xml",
        "wizard/ir_attachment_version_views.xml",
        "wizard/ir_attachment_share_views.xml",
        "wizard/folder_share_views.xml",
        "views/templates.xml",
        "views/dms_views.xml",
        "views/ir_attachment_views.xml",
        "report/attachment_summary_report_views.xml",
        "report/attachment_summary_report_templates.xml",
        "report/dms_reports.xml",
    ],
    "qweb": [
        "static/src/xml/dashboard_templates.xml",
        "static/src/xml/attachment_preview.xml",
    ],
    "demo": ["data/dms_demo.xml"],
    "installable": True,
    "application": True,
}
