from . import hotel_reservation_financial_report
from . import hotel_reservation_payment_report
from . import hotel_reservation_invoice_report
from . import hotel_reservation_tax_report
from . import hotel_reservation_tax_report_xlsx
from . import payment_invoice_management_report
from . import hotel_reservation_monthly_report
from . import hotel_reservation_promissory_report
from . import ir_actions_report
