{
    "name": "Real Estate",
    "version": "14.0.1.0.0",
    "author": "Hadooc",
    "depends": ["base_address_city", "product", "account", "crm", "hr_expense"],
    "data": [
        "security/real_estate_security.xml",
        "security/ir.model.access.csv",
        "data/real_estate_data.xml",
        "views/menu_views.xml",
        "views/res_country_views.xml",
        "views/res_city_views.xml",
        "views/realestate_base_views.xml",
        "views/realestate_building_views.xml",
        "views/building_unit_views.xml",
        "views/installment_template_views.xml",
        "views/realestate_contract_views.xml",
        "views/unit_reservation_views.xml",
        "views/sale_commission_views.xml",
    ],
    "demo": [],
    "license": "AGPL-3",
    "installable": True,
    "application": True,
}
